source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               Application.e4xmi,\
               icons/,\
               launch/,\
               about.html,\
               about_files/
jre.compilation.profile = JavaSE-21
src.includes = about.html,\
               about_files/
