source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               about.html,\
               about_files/
javacDefaultEncoding.. = UTF-8
src.includes = about.html,\
               about_files/
