source.. = src/,\
           test/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               README.md,\
               about.html,\
               about_files/
src.includes = about.html,\
               about_files/
