/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Colors",
{
  title : "Alternative Demo Theme",
  colors : {
    "button.CHECK.background" : [ 255, 255, 255 ],
    "button.CHECK.foreground" : [ 112, 94, 66 ],
    "button.FLAT.pressed.background" : [ 227, 221, 158 ],
    "button.background" : [ 157, 208, 234 ],
    "button.foreground" : [ 112, 94, 66 ],
    "button.hover.background" : [ 255, 255, 255 ],
    "link.foreground" : [ 34, 139, 34 ],
    "list.background" : [ 255, 241, 161 ],
    "list.foreground" : [ 39, 64, 139 ],
    "list.selection.background" : [ 86, 160, 234 ],
    "list.selection.foreground" : [ 255, 255, 255 ],
    "list.selection.unfocused.background" : [ 192, 192, 192 ],
    "list.selection.unfocused.foreground" : [ 255, 255, 255 ],
    "menu.background" : [ 255, 255, 255 ],
    "menu.foreground" : [ 0, 0, 0 ],
    "menu.hover.background" : [ 86, 160, 234 ],
    "menu.hover.foreground" : [ 255, 255, 255 ],
    "progressbar.background" : [ 248, 248, 255 ],
    "progressbar.foreground" : [ 0, 128, 192 ],
    "shell.background" : [ 255, 255, 255 ],
    "shell.title.background" : [ 157, 208, 234 ],
    "shell.title.background.gradient" : [ 114, 114, 114 ],
    "shell.title.foreground" : [ 255, 255, 255 ],
    "shell.title.inactive.background" : [ 205, 197, 191 ],
    "shell.title.inactive.background.gradient" : [ 205, 197, 191 ],
    "shell.title.inactive.foreground" : [ 128, 128, 128 ],
    "tabfolder.background" : [ 242, 238, 189 ],
    "tabfolder.checked.background" : [ 255, 255, 255 ],
    "tabfolder.hover.background" : [ 242, 238, 189 ],
    "table.column.background" : [ 248, 248, 255 ],
    "table.column.hover.background" : [ 248, 248, 255 ],
    "table.row.line" : [ 238, 238, 238 ],
    "toolbar.background" : [ 255, 255, 255 ],
    "toolbar.foreground" : [ 112, 94, 66 ],
    "toolbar.hover.background" : [ 238, 233, 233 ],
    "toolbar.hover.foreground" : [ 112, 94, 66 ],
    "tree.column.background" : [ 248, 248, 255 ],
    "tree.column.hover.background" : [ 248, 248, 255 ],
    "widget.background" : [ 255, 255, 255 ],
    "widget.darkshadow" : [ 133, 135, 140 ],
    "widget.foreground" : [ 112, 94, 66 ],
    "widget.graytext" : [ 167, 166, 170 ],
    "widget.highlight" : [ 255, 255, 255 ],
    "widget.info.background" : [ 255, 255, 196 ],
    "widget.info.foreground" : [ 0, 0, 0 ],
    "widget.lightshadow" : [ 220, 223, 228 ],
    "widget.selection-marker" : [ 86, 160, 234 ],
    "widget.shadow" : [ 167, 166, 170 ],
    "widget.thinborder" : [ 214, 194, 210 ]
  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Borders",
{
  title : "Alternative Demo Theme",
  extend : org.eclipse.swt.theme.BordersBase,
  borders : {
    "button.BORDER.border" : { width : 2, color : [ "widget.lightshadow", "widget.darkshadow", "widget.darkshadow", "widget.lightshadow" ], innerColor : [ "widget.highlight", "widget.shadow", "widget.shadow", "widget.highlight" ] },
    "button.BORDER.pressed.border" : { width : 2, color : [ "widget.shadow", "widget.highlight", "widget.highlight", "widget.shadow" ], innerColor : [ "widget.darkshadow", "widget.lightshadow", "widget.lightshadow", "widget.darkshadow" ] },
    "button.FLAT.border" : { width : 1, color : "black" },
    "button.FLAT.pressed.border" : { width : 1, color : "black" },
    "button.border" : { width : 2, color : "#1695d4" },
    "button.pressed.border" : { width : 1, color : [ "widget.shadow", "widget.highlight", "widget.highlight", "widget.shadow" ] },
    "control.BORDER.border" : { width : 2, color : [ "widget.shadow", "widget.highlight", "widget.highlight", "widget.shadow" ], innerColor : [ "widget.darkshadow", "widget.lightshadow", "widget.lightshadow", "widget.darkshadow" ] },
    "control.border" : { width : 0 },
    "group.frame.border" : { width : 3, style : "double", color : "#56a0ea" },
    "label.BORDER.border" : { width : 1, color : [ "widget.shadow", "widget.highlight", "widget.highlight", "widget.shadow" ] },
    "label.border" : { width : 0 },
    "menu.border" : { width : 1, color : "#1695d4" },
    "shell.BORDER.border" : { width : 3, color : "#1695d4" },
    "shell.border" : { width : 1, color : "gray" },
    "text.BORDER.border" : { width : 1, color : "#1695d4" },
    "text.border" : { width : 0 }
  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Fonts",
{
  title : "Alternative Demo Theme",
  fonts : {
    "button.font" : { family: ["Arial" ,"Helvetica" ,"sans-serif"], size: 12, bold: true },
    "group.label.font" : { family: ["Arial" ,"Helvetica" ,"sans-serif"], size: 12, bold: true },
    "shell.title.font" : { family: ["Trebuchet MS" ,"Arial" ,"Helvetica" ,"sans-serif"], size: 15, bold: true },
    "widget.font" : { family: ["Helvetica" ,"Arial" ,"sans-serif"], size: 12 }
  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Icons",
{
  title : "Alternative Demo Theme",
  icons : {
    "uri" : "resource/themes/Custom_1/widgets"
  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Widgets",
{
  title : "Alternative Demo Theme",
  widgets : {
    "uri" : "resource/themes/Custom_1/widgets"
  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1Appearances",
{
  title : "Alternative Demo Theme",
  extend : org.eclipse.swt.theme.AppearancesBase,
  appearances : {


  "hyperlink" : {
    style : function( states ) {
      return {
        font: "widget.font",
        cursor : "default",
        spacing : 4,
        width : "auto",
        height : "auto",
        horizontalChildrenAlign : "center",
        verticalChildrenAlign : "middle"
      }
    }
  }

  }
} );
/* RAP theme file generated by QxTheme. */
qx.Theme.define( "org.eclipse.swt.theme.Custom_1",
{
  title : "Alternative Demo Theme",
  meta : {
    "color" : org.eclipse.swt.theme.Custom_1Colors,
    "border" : org.eclipse.swt.theme.Custom_1Borders,
    "font" : org.eclipse.swt.theme.Custom_1Fonts,
    "icon" : org.eclipse.swt.theme.Custom_1Icons,
    "widget" : org.eclipse.swt.theme.Custom_1Widgets,
    "appearance" : org.eclipse.swt.theme.Custom_1Appearances
  }
} );
dim = org.eclipse.swt.theme.Dimensions.getInstance();
dim.set( "button.padding", "org.eclipse.swt.theme.Custom_1", [ 2, 2, 2, 2 ] );
dim.set( "button.spacing", "org.eclipse.swt.theme.Custom_1", 2 );
dim.set( "group.label.margin", "org.eclipse.swt.theme.Custom_1", [ 1, 10, 1, 10 ] );
dim.set( "group.label.padding", "org.eclipse.swt.theme.Custom_1", [ 0, 6, 0, 6 ] );
dim.set( "group.margin", "org.eclipse.swt.theme.Custom_1", [ 8, 0, 0, 0 ] );
dim.set( "group.padding", "org.eclipse.swt.theme.Custom_1", [ 8, 2, 2, 2 ] );
dim.set( "menu.padding", "org.eclipse.swt.theme.Custom_1", [ 0, 0, 0, 0 ] );
dim.set( "shell.button.margin", "org.eclipse.swt.theme.Custom_1", [ 0, 2, 8, 0 ] );
dim.set( "shell.padding", "org.eclipse.swt.theme.Custom_1", [ 5, 5, 5, 5 ] );
dim.set( "shell.title.height", "org.eclipse.swt.theme.Custom_1", 25 );
dim.set( "shell.title.margin", "org.eclipse.swt.theme.Custom_1", [ 0, 0, 0, 0 ] );
dim.set( "shell.title.padding", "org.eclipse.swt.theme.Custom_1", [ 2, 5, 2, 2 ] );
dim.set( "table.checkbox.width", "org.eclipse.swt.theme.Custom_1", 21 );
dim.set( "text.SINGLE.padding", "org.eclipse.swt.theme.Custom_1", [ 2, 3, 2, 3 ] );
delete dim;
